image: trion/ng-cli-karma

stages:
  - test
  # - e2e
  - deploy

before_script:
  - apt-get upgrade
  - apt install chromium-bsu
  - apt list --installed
  - ls -1 /usr/bin
  - npm install || true

cache:
  paths: 
    - node_modules/
    - /usr/bin/chromium-browser

test:
  script: 
    - 'ng test --watch=false'
  tags:
    - merp-web-runner

# e2e: 
#   script:
#     - 'ng e2e' 
#   tags:
#     - merp-web-runner

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash ./deploy-production.sh