image: trion/ng-cli-karma

# Estados por los cuales debe pasar el CI
stages:
  - test
  - e2e
  - deploy

before_script:
  - npm install || true

cache:
  paths: 
    - node_modules/

# Se realizan las pruebas unitarias
test:
  script: 
    - npm install || true
    - 'ng test --watch=false'
  tags:
    - merp-web-runner

# Se realizan pruebas e2e
e2e:
  script:
    - npm install || true
    - 'ng e2e'
  tags:
    - merp-web-runner

# Se inicia el estado de despliegue
deploy:
  only:
    - master
  before_script:
    - "which ssh-agent || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # - ng build --prod
  script:
    - bash .gitlab-deploy.sh   
  environment:     
    name: production     
    url: https://3.13.185.75
  tags:
    - merp-web-runner
