image: node:8.9.0

stages:
  - test
  - e2e
  - deploy

before_script:
  - npm install || true
  - npm install -g @angular/cli

cache:
  paths: 
    - node_modules/

test:
  script: 
    - 'ng test
      --code-coverage 
      --reporters=coverage-istanbul,progress 
      --print summary 
      --single-run 
      --progress=false'
  coverage: '/^Statements\s*:\s*([^%]+)/'
  tags:
    - merp-web-runner

e2e: 
  script:
    - 'ng e2e
      --progress=false' 
  tags:
    - merp-web-runner

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash ./deploy-production.sh