image: trion/ng-cli-karma

# Estados por los cuales debe pasar el CI
stages:
  - test
  # - e2e
  - deploy

# Se realizan las pruebas unitarias
test:
  cache:
    paths: 
      - node_modules/
  script: 
    # - npm install || true
    # - 'ng test --watch=false'
    - echo "Pass"
  tags:
    - merp-web-runner

# Se realizan pruebas e2e
# e2e:
#   cache:
#     paths:
#       - node_modules/
#   script:
#     - npm install || true
#     - 'ng e2e'
#   tags:
#     - merp-web-runner

# Se inicia el estado de despliegue
deploy:
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  script:
    - bash ./deploy/deploy-production.sh
  tags:
    - merp-web-runner
