image: trion/ng-cli-karma

# Estados por los cuales debe pasar el CI
stages:
  - test
  - e2e
  - deploy

# Utilizamos la cache para no instalar de nuevo depencias 


# Se realizan las pruebas unitarias
test:
  cache:
    paths: 
      - node_modules/
  script: 
    - npm install || true
    - 'ng test --watch=false'
  tags:
    - merp-web-runner

# Se realizan pruebas e2e
e2e:
  cache:
    paths:
      - node_modules/
  script:
    - npm install || true
    - 'ng e2e'
  tags:
    - merp-web-runner

# Se inicia el estado de despliegue
deploy:
  only:
    - master
  before_script:
     - mkdir -p ~/.ssh
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash .gitlab-deploy.sh
  environment:
    name: production
    url: http://3.13.185.75