image: node:10.16

stages:
  - test
  # - e2e
  - deploy

before_script:
  - ls -1 /usr/bin
  - npm install || true
  - npm install -g @angular/cli

cache:
  paths: 
    - node_modules/

test:
  script: 
    - 'ng test --watch=false'
  tags:
    - merp-web-runner

# e2e: 
#   script:
#     - 'ng e2e' 
#   tags:
#     - merp-web-runner

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash ./deploy-production.sh