image: node:10.16

stages:
  - test
  - e2e
  - deploy

before_script:
  - npm install || true

cache:
  paths: 
    - node_modules/

test:
  script: 
    - 'ng test'
  coverage: '/^Statements\s*:\s*([^%]+)/'
  tags:
    - merp-web-runner

e2e: 
  script:
    - 'ng e2e' 
  tags:
    - merp-web-runner

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash ./deploy-production.sh